# Generated by Django 5.0.6 on 2024-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_street_adress_useraddress_street_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankruptcyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
    ]
