# Generated by Django 5.0.6 on 2024-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=40)),
                ('task_description', models.CharField(max_length=200)),
                ('task_assing_dt', models.DateField()),
            ],
        ),
    ]
