# Generated by Django 5.0.6 on 2024-06-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_remove_category_tasks'),
        ('task_app', '0002_rename_task_assing_dt_task_task_assigned_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category_app.category'),
            preserve_default=False,
        ),
    ]
