# Generated by Django 5.0.6 on 2024-06-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albums',
            new_name='musician',
        ),
    ]
